### ISSUE TITLE
question about document source content

### ISSUE THREAD

**Issue by xtyuns** [qos-ch/logback-site#11]
hi ceki, I have 2 questions:
1. When I was reading the logback manual I found a problem in the chapter about [configuration](https://logback.qos.ch/manual/configuration.html#logback.statusLC): the shorthand for OnConsoleStatusListener in system property is [`SYSOUT`](https://github.com/qos-ch/logback/blob/5105d7a4fdf2bec03e531b59c30778c244c728c8/logback-core/src/main/java/ch/qos/logback/core/util/StatusListenerConfigHelper.java#L34) instead of `STDOUT`
![image](https://github.com/qos-ch/logback-site/assets/41326335/201a6267-6431-4896-8290-8248dab866ed)
2. When I wanted to fix this description, I found this part to be inconsistent on this repository and on the page, this looks like the repository and the page are out of sync.

**Comment by ceki** [comment]
@xtyuns Thank you for  opening this ticket. It is much appreciated.
